version: '3'

services:
   libfrp:
      build:
         context: ../
         dockerfile: docker/libfrp/Dockerfile
      image: rfrp_libfrp_image
      container_name: rfrp_libfrp
      depends_on:
         - redis
      volumes:
         - ..:/src
         - context:/context
      ports:
         - "${BIND_PORT}:${BIND_PORT}"
         - "${HTTP_PORT}:${HTTP_PORT}"
      environment:
         - DOMAIN=${DOMAIN}
         - RD_HOST=${RD_HOST}
         - BIND_PORT=${BIND_PORT}
         - HTTP_PORT=${HTTP_PORT}
   user_api:
      build:
         context: ../
         dockerfile: docker/user_api/Dockerfile
      image: rfrp_user_api_image
      container_name: rfrp_user_api
      depends_on:
         - db
         - redis
      volumes:
         - ..:/src
         - context:/context
      ports:
         - "${API_PORT}:${API_PORT}"
      environment:
         - API_PORT=${API_PORT}
         - DOMAIN=${DOMAIN}
         - RD_HOST=${RD_HOST}
         - DB_HOST=${DB_HOST}
         - DB_USER=${DB_USER}
         - DB_PASS=${DB_PASS}
         - DB_NAME=${DB_NAME}
   db:
      container_name: ${DB_HOST}
      image: mysql:8
      restart: always
      expose:
         - '3306'
      ports:
         - "13306:3306"
      command: --secure-file-priv=
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
         - ../db/data:/var/lib/mysql
         - ../db/init:/docker-entrypoint-initdb.d/:ro
         - context:/context
   redis:
      container_name: ${RD_HOST}
      image: redis:7
      restart: always
      ports:
         - '${RD_PORT}:${RD_PORT}'
      volumes:
         - ../cache/data:/data
volumes:
   context:
   
